export type SourceItem = {
  name: string;
  chunk: string;
  score: number;
  vectorScore?: number;
  tag: "Primary" | "Support";
  content: string;
};

export type PhaseItem = {
  phase: string;
  title: string;
  date: string;
  color: string;
  tasks: string[];
  cite: string;
};

export type ActivityItem = {
  actor: string;
  action: string;
  time: string;
  color: string;
  stepIndex: number;
};

export type ToolCallItem = {
  name: string;
  time: string;
  iconKey: "search" | "file" | "checks" | "wrench";
  stepIndex: number;
};

export type ProjectConfig = {
  id: string;
  name: string;
  runId: string;
  prompt: string;
  metadata: string;
  agentLabel: string;
  sources: SourceItem[];
  plan: string[];
  output: {
    title: string;
    subtitle: string;
    summary: string;
    phases: PhaseItem[];
  };
  activities: ActivityItem[];
  tools: ToolCallItem[];
  evals?: {
    retrievalQuality: number;
    retrievalQualityReasoning: string;
    faithfulness: number;
    faithfulnessReasoning: string;
    citationAccuracy: number;
    citationAccuracyReasoning: string;
  };
};

export const projectsData: Record<string, ProjectConfig> = {
  "compliance-roadmap": {
    id: "compliance-roadmap",
    name: "Compliance roadmap",
    runId: "R-2048",
    prompt: "Create a roadmap based on compliance requirements.",
    metadata: "12 documents · Started 9:42 AM · GPT-4.1",
    agentLabel: "Acme, Inc.",
    sources: [
      {
        name: "EU AI Act — Controls.pdf",
        chunk: "§4.2 · Risk management",
        score: 96,
        tag: "Primary",
        content: "High-risk AI systems must establish and maintain an ongoing risk management framework. Standard controls dictate assigning accountability, performing hazard classification reviews, and validating output integrity against reference datasets."
      },
      {
        name: "SOC 2 Control Matrix.pdf",
        chunk: "CC6.1 · Logical access",
        score: 93,
        tag: "Primary",
        content: "The entity restricts logical access to security-relevant systems. Access authorizations must be reviewed quarterly, security credentials managed through centralized directories, and vendor assessment workflows refreshed on a consistent cadence."
      },
      {
        name: "Data Retention Policy.pdf",
        chunk: "p. 12 · Retention schedule",
        score: 89,
        tag: "Support",
        content: "Under section 12, logs documenting AI system operations, retrieval sources, and user prompt inputs must be retained for audit purposes. The data retention schedule specifies a 7-year shelf life for security-relevant operations history."
      },
      {
        name: "Vendor Security Standard.pdf",
        chunk: "§7 · Review cadence",
        score: 84,
        tag: "Support",
        content: "Third-party services handling sensitive company data must undergo a security review before onboarding. Follow-up evaluations should follow a regular yearly review cadence or occur immediately upon any critical change in vendor architecture."
      }
    ],
    plan: [
      "Analyze uploaded compliance and policy files for risk triggers.",
      "Decompose criteria into standard governance, operational, and assurance goals.",
      "Synthesize a phased timeline aligned with compliance target dates.",
      "Verify generated claims against referenced policy source chunks."
    ],
    output: {
      title: "Compliance readiness roadmap",
      subtitle: "Generated by Builder · 4 sources cited",
      summary: "A three-phase program to align Acme’s AI operations with current compliance requirements. The sequence prioritizes foundational governance before operational controls and ongoing assurance.",
      phases: [
        {
          phase: "Phase 01",
          title: "Governance foundation",
          date: "July 2026",
          color: "bg-peach",
          tasks: ["Assign accountable AI system owners", "Document risk classification criteria", "Approve data retention schedule"],
          cite: "EU AI Act §4.2"
        },
        {
          phase: "Phase 02",
          title: "Operational controls",
          date: "August 2026",
          color: "bg-lavender",
          tasks: ["Implement quarterly access reviews", "Refresh vendor assessment workflow", "Add evidence collection checkpoints"],
          cite: "SOC 2 CC6.1"
        },
        {
          phase: "Phase 03",
          title: "Continuous assurance",
          date: "September 2026",
          color: "bg-blue",
          tasks: ["Launch monthly control monitoring", "Run first internal readiness review", "Publish executive risk dashboard"],
          cite: "Vendor Standard §7"
        }
      ]
    },
    activities: [
      { actor: "System", action: "Run initialized", time: "27s ago", color: "bg-[#e8e2d9]", stepIndex: 0 },
      { actor: "Planner", action: "Decomposed task into 3-phase plan", time: "25s ago", color: "bg-peach", stepIndex: 1 },
      { actor: "Knowledge", action: "Searched vector database for criteria", time: "22s ago", color: "bg-blue", stepIndex: 2 },
      { actor: "Knowledge", action: "Selected 4 source chunks from 12 docs", time: "18s ago", color: "bg-blue", stepIndex: 3 },
      { actor: "Builder", action: "Synthesized draft response roadmap", time: "13s ago", color: "bg-mint", stepIndex: 4 },
      { actor: "Builder", action: "Generated final output roadmap", time: "6s ago", color: "bg-mint", stepIndex: 5 },
      { actor: "Knowledge", action: "Verified 9 claims against active context", time: "3s ago", color: "bg-lavender", stepIndex: 6 },
      { actor: "System", action: "Run complete and audit trail sealed", time: "now", color: "bg-[#e8e2d9]", stepIndex: 7 }
    ],
    tools: [
      { name: "vector.search", time: "412 ms", iconKey: "search", stepIndex: 2 },
      { name: "document.read", time: "86 ms", iconKey: "file", stepIndex: 3 },
      { name: "claims.verify", time: "1.2 s", iconKey: "checks", stepIndex: 6 }
    ]
  },
  "vendor-review": {
    id: "vendor-review",
    name: "Vendor review",
    runId: "R-2049",
    prompt: "Analyze the vendor security assessment for Acme's new cloud provider.",
    metadata: "3 documents · Started 11:15 AM · GPT-4.1",
    agentLabel: "Security Team",
    sources: [
      {
        name: "Cloud Provider SOC 2.pdf",
        chunk: "CC6.3 · Key management",
        score: 95,
        tag: "Primary",
        content: "Cryptographic keys are managed using automated hardware security modules (HSM). Access to keys requires multi-party authorization. Key rotation occurs automatically every 90 days or immediately upon key custodian changes."
      },
      {
        name: "Vendor Security Questionnaire.pdf",
        chunk: "§2 · Encryption",
        score: 91,
        tag: "Primary",
        content: "Data in transit is encrypted using TLS 1.3. Cryptographic suites prioritizing perfect forward secrecy are enforced. Data at rest is encrypted in all environments using AES-256 with keys stored securely in HSMs."
      },
      {
        name: "Encryption Standard.pdf",
        chunk: "p. 3 · TLS requirements",
        score: 88,
        tag: "Support",
        content: "Corporate policies require third-party connections to employ minimum TLS 1.2, strongly recommending TLS 1.3. Deprecated legacy protocols such as SSL v3, TLS 1.0, and TLS 1.1 must be actively blocked at firewall thresholds."
      }
    ],
    plan: [
      "Review cryptographic key management practices of the provider.",
      "Check transmission and storage encryption specifications.",
      "Cross-reference vendor mechanisms with corporate Encryption Standards.",
      "Highlight exceptions and formulate the final security report."
    ],
    output: {
      title: "Cloud Vendor Security Audit",
      subtitle: "Generated by Builder · 3 sources cited",
      summary: "An audit assessing the security compliance of the new cloud vendor. The review outlines encryption standards, key protection policies, and lists mandatory improvements.",
      phases: [
        {
          phase: "Phase 01",
          title: "Encryption & key safety",
          date: "July 2026",
          color: "bg-peach",
          tasks: ["Verify AES-256 key rotation policy", "Ensure TLS 1.3 enforcement on all endpoints", "Check HSM backing for root certificates"],
          cite: "Encryption Standard p. 3"
        },
        {
          phase: "Phase 02",
          title: "Identity & access controls",
          date: "August 2026",
          color: "bg-lavender",
          tasks: ["Review multi-factor authentication enforcement", "Confirm principle of least privilege in console", "Establish role-based access for vendor personnel"],
          cite: "Cloud Provider SOC 2"
        },
        {
          phase: "Phase 03",
          title: "Logging & audit trail",
          date: "September 2026",
          color: "bg-blue",
          tasks: ["Configure central audit log forwarding", "Setup real-time alert for policy violations", "Perform initial third-party access audit"],
          cite: "Vendor Questionnaire"
        }
      ]
    },
    activities: [
      { actor: "System", action: "Run initialized", time: "20s ago", color: "bg-[#e8e2d9]", stepIndex: 0 },
      { actor: "Planner", action: "Identified 3 assessment review areas", time: "18s ago", color: "bg-peach", stepIndex: 1 },
      { actor: "Knowledge", action: "Queried SOC 2 and Encryption standards", time: "15s ago", color: "bg-blue", stepIndex: 2 },
      { actor: "Knowledge", action: "Extracted 3 compliance passages", time: "12s ago", color: "bg-blue", stepIndex: 3 },
      { actor: "Builder", action: "Synthesized security assessment", time: "8s ago", color: "bg-mint", stepIndex: 4 },
      { actor: "Builder", action: "Compiled audit findings list", time: "5s ago", color: "bg-mint", stepIndex: 5 },
      { actor: "Knowledge", action: "Verified 6 safety statements", time: "2s ago", color: "bg-lavender", stepIndex: 6 },
      { actor: "System", action: "Security review completed", time: "now", color: "bg-[#e8e2d9]", stepIndex: 7 }
    ],
    tools: [
      { name: "vector.search", time: "289 ms", iconKey: "search", stepIndex: 2 },
      { name: "document.read", time: "74 ms", iconKey: "file", stepIndex: 3 },
      { name: "claims.verify", time: "880 ms", iconKey: "checks", stepIndex: 6 }
    ]
  },
  "q3-strategy": {
    id: "q3-strategy",
    name: "Q3 strategy",
    runId: "R-2050",
    prompt: "Evaluate compliance risks for our Q3 marketing and data collection strategy.",
    metadata: "5 documents · Started 2:10 PM · GPT-4.1",
    agentLabel: "Marketing Ops",
    sources: [
      {
        name: "Privacy Policy.pdf",
        chunk: "Section 3 · Cookies and Tracking",
        score: 97,
        tag: "Primary",
        content: "Our organization uses tracking cookies only after receiving explicit user opt-in consent. Cross-site tracking is disabled by default. Users have the right to withdraw consent at any time through our preference dashboard."
      },
      {
        name: "CCPA Guidelines.pdf",
        chunk: "§1798.100 · Right to Know",
        score: 92,
        tag: "Primary",
        content: "Under CCPA, California consumers have the right to request disclosure of categories and specific pieces of personal information collected. Consumers can opt out of the sale or sharing of their personal information."
      },
      {
        name: "GDPR compliance check.pdf",
        chunk: "Art 6 · Lawfulness of processing",
        score: 89,
        tag: "Support",
        content: "Data processing is lawful only if consent is obtained or processing is necessary for a contract or legal obligation. Consent must be freely given, specific, informed, and unambiguous."
      }
    ],
    plan: [
      "Review cookie tracking consent workflow against Privacy Policy rules.",
      "Check CCPA compliance for customer database data requests.",
      "Assess GDPR consent definitions on data sharing policies.",
      "Report findings and create a compliance correction checklist."
    ],
    output: {
      title: "Q3 Marketing Compliance Review",
      subtitle: "Generated by Builder · 3 sources cited",
      summary: "A compliance risk evaluation for Q3 marketing. This report checks tracking consent mechanisms, data rights administration, and third-party data handlers.",
      phases: [
        {
          phase: "Phase 01",
          title: "Consent mechanics",
          date: "July 2026",
          color: "bg-peach",
          tasks: ["Audit cookie consent banner on landing pages", "Ensure explicit opt-in for cross-site tracking", "Provide clear link for 'Do Not Sell My Info'"],
          cite: "Privacy Policy Section 3"
        },
        {
          phase: "Phase 02",
          title: "Data processing & rights",
          date: "August 2026",
          color: "bg-lavender",
          tasks: ["Implement automated user data deletion request tool", "Document compliance under California Right to Know laws", "Restrict marketing list access on customer database"],
          cite: "CCPA §1798.100"
        },
        {
          phase: "Phase 03",
          title: "Third-party data sharing",
          date: "September 2026",
          color: "bg-blue",
          tasks: ["Review data sharing clauses with external ad nets", "Verify location-based processing rules for EU users", "Perform annual training for marketing data handlers"],
          cite: "GDPR Art 6"
        }
      ]
    },
    activities: [
      { actor: "System", action: "Run initialized", time: "22s ago", color: "bg-[#e8e2d9]", stepIndex: 0 },
      { actor: "Planner", action: "Scheduled 4 assessment areas", time: "20s ago", color: "bg-peach", stepIndex: 1 },
      { actor: "Knowledge", action: "Queried cookie policy and state privacy acts", time: "17s ago", color: "bg-blue", stepIndex: 2 },
      { actor: "Knowledge", action: "Selected 3 key privacy chapters", time: "14s ago", color: "bg-blue", stepIndex: 3 },
      { actor: "Builder", action: "Drafted marketing risk assessment", time: "10s ago", color: "bg-mint", stepIndex: 4 },
      { actor: "Builder", action: "Refined compliance instructions", time: "7s ago", color: "bg-mint", stepIndex: 5 },
      { actor: "Knowledge", action: "Verified 8 legal claims", time: "4s ago", color: "bg-lavender", stepIndex: 6 },
      { actor: "System", action: "Marketing review completed", time: "now", color: "bg-[#e8e2d9]", stepIndex: 7 }
    ],
    tools: [
      { name: "vector.search", time: "315 ms", iconKey: "search", stepIndex: 2 },
      { name: "document.read", time: "92 ms", iconKey: "file", stepIndex: 3 },
      { name: "claims.verify", time: "1.4 s", iconKey: "checks", stepIndex: 6 }
    ]
  },
  "policy-refresh": {
    id: "policy-refresh",
    name: "Policy refresh",
    runId: "R-2051",
    prompt: "Draft updates for our company-wide AI Acceptable Use Policy.",
    metadata: "2 documents · Started 4:30 PM · GPT-4.1",
    agentLabel: "HR & Governance",
    sources: [
      {
        name: "Corporate Governance handbook.pdf",
        chunk: "Ch. 5 · Risk Oversight",
        score: 94,
        tag: "Primary",
        content: "Risk oversight committees must review all generative AI utilization. Use of corporate IP in public models is forbidden without structural data protection agreements."
      },
      {
        name: "Employee handbook draft.pdf",
        chunk: "§9 · Code of Conduct",
        score: 90,
        tag: "Primary",
        content: "Employees must maintain confidential information. Disclosing corporate code, private keys, or client-sensitive details into external AI programs constitutes a security breach."
      }
    ],
    plan: [
      "Review risk oversight rules for generative AI utilization.",
      "Formulate data disclosure restrictions for employee handbook inclusion.",
      "Check monitoring compliance rules against IT controls.",
      "Generate the revised AI Acceptable Use Policy draft."
    ],
    output: {
      title: "AI Acceptable Use Policy Updates",
      subtitle: "Generated by Builder · 2 sources cited",
      summary: "Draft updates for company AI guidelines. This outline details permitted tool classifications, restrictions on data disclosure, and monitoring standards.",
      phases: [
        {
          phase: "Phase 01",
          title: "Permitted AI systems",
          date: "July 2026",
          color: "bg-peach",
          tasks: ["Publish catalog of pre-approved AI tools", "Define process for requesting new tool approvals", "Integrate compliance checks into IT procurement"],
          cite: "Corp Gov Ch. 5"
        },
        {
          phase: "Phase 02",
          title: "Data disclosure limits",
          date: "August 2026",
          color: "bg-lavender",
          tasks: ["Enforce strict ban on pasting proprietary code", "Define classification rules for sensitive data", "Install data loss prevention (DLP) proxies"],
          cite: "Employee Handbook §9"
        },
        {
          phase: "Phase 03",
          title: "Compliance monitoring",
          date: "September 2026",
          color: "bg-blue",
          tasks: ["Audit API key utilization patterns", "Run monthly acceptable use compliance reviews", "Refresh employee training on generative AI risks"],
          cite: "Corp Gov Ch. 5"
        }
      ]
    },
    activities: [
      { actor: "System", action: "Run initialized", time: "18s ago", color: "bg-[#e8e2d9]", stepIndex: 0 },
      { actor: "Planner", action: "Identified governance guidelines", time: "16s ago", color: "bg-peach", stepIndex: 1 },
      { actor: "Knowledge", action: "Queried governance and handbooks", time: "13s ago", color: "bg-blue", stepIndex: 2 },
      { actor: "Knowledge", action: "Retrieved 2 core policies", time: "10s ago", color: "bg-blue", stepIndex: 3 },
      { actor: "Builder", action: "Drafted policy amendments", time: "7s ago", color: "bg-mint", stepIndex: 4 },
      { actor: "Builder", action: "Completed updates structure", time: "4s ago", color: "bg-mint", stepIndex: 5 },
      { actor: "Knowledge", action: "Verified 5 handbook items", time: "2s ago", color: "bg-lavender", stepIndex: 6 },
      { actor: "System", action: "Acceptable use draft compiled", time: "now", color: "bg-[#e8e2d9]", stepIndex: 7 }
    ],
    tools: [
      { name: "vector.search", time: "198 ms", iconKey: "search", stepIndex: 2 },
      { name: "document.read", time: "65 ms", iconKey: "file", stepIndex: 3 },
      { name: "claims.verify", time: "680 ms", iconKey: "checks", stepIndex: 6 }
    ]
  }
};
