import { NextResponse } from "next/server";
import { db, DbChunk } from "@/lib/db";
import { getEmbedding } from "@/lib/embeddings";
import { rerank, RerankedItem } from "@/lib/reranker";
import { evaluateRun } from "@/lib/evaluator";
import { OpenAI } from "openai";
import { ProjectConfig, SourceItem } from "@/lib/project-data";

let openai: OpenAI | null = null;
if (process.env.OPENAI_API_KEY) {
  openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
}

export const dynamic = "force-dynamic";

export async function POST(req: Request) {
  try {
    const { projectId, prompt } = await req.json();
    if (!projectId || !prompt) {
      return NextResponse.json({ error: "Missing projectId or prompt" }, { status: 400 });
    }

    const project = await db.getProject(projectId);
    if (!project) {
      return NextResponse.json({ error: "Project not found" }, { status: 404 });
    }

    const startTotal = Date.now();

    // Step 1: Planner Agent - Create plan steps
    const plan = [
      `Analyze user prompt "${prompt}" for compliance risk areas.`,
      `Retrieve and rank relevant policy text chunks from indexed workspace files.`,
      `Synthesize structured readiness goals and tasks into a phased roadmap.`,
      `Run RAGAS evaluation harness to verify claims and seal run provenance.`
    ];

    // Step 2: Knowledge Vector Search
    const searchStart = Date.now();
    const queryEmbedding = await getEmbedding(prompt);
    const rawMatches = await db.getSimilaritySearchResults(queryEmbedding, 6);
    const searchDuration = Date.now() - searchStart;

    if (rawMatches.length === 0) {
      return NextResponse.json({ 
        error: "Your workspace document library is empty. Please upload some text or PDF files in the Documents tab first!" 
      }, { status: 400 });
    }

    // Step 3: Reranker
    const rerankStart = Date.now();
    const rerankedList = await rerank(prompt, rawMatches, 4);
    const rerankDuration = Date.now() - rerankStart;

    // Map reranked chunks to SourceItem format for UI
    const sources: SourceItem[] = rerankedList.map((item) => {
      // Find original doc name
      const docName = item.chunk.documentId.replace("doc-", "Doc "); // default fallback
      return {
        name: docName,
        chunk: `§${item.chunk.chunkIndex + 1} · Text snippet`,
        score: item.rerankScore,      // This is the main Match score (Rerank)
        vectorScore: item.vectorScore, // Storing vector score
        tag: item.rerankScore > 75 ? "Primary" : "Support",
        content: item.chunk.content
      };
    });

    // Populate source document names from database
    const docs = await db.getDocuments();
    sources.forEach(source => {
      // Find matching document by ID
      const matchingDoc = docs.find(d => source.name.includes(d.id) || d.id === source.name.replace("Doc ", "doc-"));
      if (matchingDoc) {
        source.name = matchingDoc.name;
      }
    });

    // Step 4: Builder Synthesis (LLM or Fallback Template)
    let output: ProjectConfig["output"];
    const builderStart = Date.now();

    if (openai) {
      try {
        const response = await openai.chat.completions.create({
          model: "gpt-4o-mini",
          response_format: { type: "json_object" },
          messages: [
            {
              role: "system",
              content: `You are the Builder Agent. Your job is to synthesize a structured compliance roadmap based on the retrieved document context.
Respond ONLY with a JSON object containing:
- title: string (e.g., "Compliance readiness roadmap for ...")
- subtitle: string (e.g., "Generated by Builder · X sources cited")
- summary: string (high-level 2-sentence summary)
- phases: array of objects, containing:
  - phase: string (e.g. "Phase 01")
  - title: string (e.g. "Governance setup")
  - date: string (e.g. "July 2026")
  - color: string (choose one of: "bg-peach", "bg-lavender", "bg-blue")
  - tasks: array of strings (3 concrete checklist tasks)
  - cite: string (a clean citation pointing to the document name and section, e.g. "SOC 2 CC6.1" or "EU AI Act §4.2")`
            },
            {
              role: "user",
              content: `Create a compliance roadmap for this query: "${prompt}"
Using this context:
${rerankedList.map((item, idx) => `[Source #${idx + 1}] (${item.chunk.documentId}):
"${item.chunk.content}"`).join("\n\n")}`
            }
          ]
        });

        const outputText = response.choices[0].message.content;
        if (outputText) {
          output = JSON.parse(outputText);
        } else {
          throw new Error("Empty OpenAI response");
        }
      } catch (err) {
        console.warn("OpenAI synthesis failed, falling back to local template generator:", err);
        output = generateLocalTemplateOutput(prompt, rerankedList, docs);
      }
    } else {
      output = generateLocalTemplateOutput(prompt, rerankedList, docs);
    }
    const builderDuration = Date.now() - builderStart;

    // Step 5: Eval Harness (Retrieval Quality, Faithfulness, Citation Accuracy)
    const evalStart = Date.now();
    
    // Build citation records for the evaluator
    const citations = output.phases.map(p => {
      // Find matching source text
      const matchingSource = sources.find(s => 
        p.cite.toLowerCase().includes(s.name.toLowerCase().split(".")[0]) ||
        s.content.toLowerCase().includes(p.cite.toLowerCase())
      );
      return {
        cite: p.cite,
        content: matchingSource ? matchingSource.content : (sources[0]?.content || "")
      };
    });

    const evals = await evaluateRun(
      prompt,
      rerankedList.map(item => item.chunk),
      JSON.stringify(output),
      citations
    );
    const evalDuration = Date.now() - evalStart;

    // Construct execution events
    const timestampStr = "now";
    const activities = [
      { actor: "System", action: "Run initialized", time: "27s ago", color: "bg-[#e8e2d9]", stepIndex: 0 },
      { actor: "Planner", action: `Decomposed task into ${output.phases.length}-phase plan`, time: "24s ago", color: "bg-peach", stepIndex: 1 },
      { actor: "Knowledge", action: `Scanned database vector index (cosine matching)`, time: "20s ago", color: "bg-blue", stepIndex: 2 },
      { actor: "Knowledge", action: `Selected & reranked ${sources.length} matching passages`, time: "16s ago", color: "bg-blue", stepIndex: 3 },
      { actor: "Builder", action: "Synthesized draft response roadmap", time: "11s ago", color: "bg-mint", stepIndex: 4 },
      { actor: "Builder", action: "Generated final output roadmap with claims", time: "6s ago", color: "bg-mint", stepIndex: 5 },
      { actor: "Knowledge", action: `Verified claims (Scores - Faithfulness: ${evals.faithfulness}%)`, time: "3s ago", color: "bg-lavender", stepIndex: 6 },
      { actor: "System", action: "Run complete and audit trail sealed", time: timestampStr, color: "bg-[#e8e2d9]", stepIndex: 7 }
    ];

    // Tool executions log
    const totalDuration = Date.now() - startTotal;
    const tools = [
      { name: "vector.search", time: `${searchDuration} ms`, iconKey: "search" as const, stepIndex: 2 },
      { name: "cohere.rerank", time: `${rerankDuration} ms`, iconKey: "wrench" as const, stepIndex: 3 },
      { name: "builder.synthesis", time: `${(builderDuration / 1000).toFixed(2)} s`, iconKey: "file" as const, stepIndex: 4 },
      { name: "claims.verify", time: `${(evalDuration / 1000).toFixed(2)} s`, iconKey: "checks" as const, stepIndex: 6 }
    ];

    // Save project configuration with new run
    const updatedProject: ProjectConfig = {
      ...project,
      runId: `R-${Math.floor(2000 + Math.random() * 8000)}`,
      prompt,
      metadata: `${docs.length} documents · Started ${new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} · RAG v1.2`,
      sources,
      plan,
      output,
      activities,
      tools,
      evals
    };

    await db.saveProject(projectId, updatedProject);
    return NextResponse.json(updatedProject);
  } catch (err: any) {
    console.error("POST run failed:", err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}

// Fallback rule-based generator when OpenAI is not configured
function generateLocalTemplateOutput(prompt: string, reranked: RerankedItem[], docs: any[]): ProjectConfig["output"] {
  const cleanPrompt = prompt.toLowerCase();
  
  // Extract sentences with keywords
  const sentences: string[] = [];
  reranked.forEach(item => {
    const lines = item.chunk.content.split(/[.!?]+/).map(s => s.trim()).filter(s => s.length > 10);
    sentences.push(...lines);
  });

  const getDocName = (docId: string) => {
    const d = docs.find(doc => doc.id === docId);
    return d ? d.name.replace(".pdf", "").replace(".txt", "") : "Source Document";
  };

  // Build tasks from extracted text
  const taskPool = sentences.filter(s => 
    s.toLowerCase().includes("must") || 
    s.toLowerCase().includes("should") || 
    s.toLowerCase().includes("require") || 
    s.toLowerCase().includes("control") ||
    s.toLowerCase().includes("audit") ||
    s.toLowerCase().includes("access")
  );

  const t1 = taskPool[0] || "Review compliance and operational risks of system processes";
  const t2 = taskPool[1] || "Configure authorization credentials and quarterly checks";
  const t3 = taskPool[2] || "Establish logs retention schedule and security criteria";
  const t4 = taskPool[3] || "Refresh vendor assessments and audit data transmission";
  const t5 = taskPool[4] || "Configure logging and secure credentials backup";
  const t6 = taskPool[5] || "Perform internal readiness assessment and audit access logs";

  return {
    title: "Synthesized compliance roadmap",
    subtitle: `Generated by Builder · ${Math.min(3, reranked.length)} sources cited`,
    summary: `A customized roadmap addressing compliance items. Developed dynamically using matching clauses from ${getDocName(reranked[0].chunk.documentId)} and adjacent document library assets.`,
    phases: [
      {
        phase: "Phase 01",
        title: "Governance Setup",
        date: "July 2026",
        color: "bg-peach",
        tasks: [
          t1.length > 80 ? t1.slice(0, 80) + "..." : t1,
          t2.length > 80 ? t2.slice(0, 80) + "..." : t2,
          "Document data retention schedules"
        ],
        cite: `${getDocName(reranked[0].chunk.documentId)}`
      },
      {
        phase: "Phase 02",
        title: "Operational Controls",
        date: "August 2026",
        color: "bg-lavender",
        tasks: [
          t3.length > 80 ? t3.slice(0, 80) + "..." : t3,
          t4.length > 80 ? t4.slice(0, 80) + "..." : t4,
          "Audit logic access logs and permissions"
        ],
        cite: reranked[1] ? `${getDocName(reranked[1].chunk.documentId)}` : `${getDocName(reranked[0].chunk.documentId)}`
      },
      {
        phase: "Phase 03",
        title: "Assurance & Verification",
        date: "September 2026",
        color: "bg-blue",
        tasks: [
          t5.length > 80 ? t5.slice(0, 80) + "..." : t5,
          t6.length > 80 ? t6.slice(0, 80) + "..." : t6,
          "Sealed audit logs backup validation"
        ],
        cite: reranked[2] ? `${getDocName(reranked[2].chunk.documentId)}` : `${getDocName(reranked[0].chunk.documentId)}`
      }
    ]
  };
}
